drop table product;
create table product(
    id bigint generated by default as identity,
    name varchar(100) not null,
    brand varchar(100) not null,
    price real not null,
    quantity int not null
);

insert into product(name,brand,price,quantity) values('T-shit', 'US POLO', 4000.00, 6);
insert into product(name,brand,price,quantity) values('T-shit', 'Tommy Hilfiger', 3500.00, 4);